/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form kalkulator.java
     */
    String Bilangan = "";
    double jumlah,bil1,bil2;
    int pilih;
    
    public kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        lima = new javax.swing.JButton();
        sembilan = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        bttambah = new javax.swing.JButton();
        enam = new javax.swing.JButton();
        btkurang = new javax.swing.JButton();
        delapan = new javax.swing.JButton();
        dua = new javax.swing.JButton();
        tiga = new javax.swing.JButton();
        btbagi = new javax.swing.JButton();
        empat = new javax.swing.JButton();
        nol = new javax.swing.JButton();
        btkoma = new javax.swing.JButton();
        btsamadengan = new javax.swing.JButton();
        satu = new javax.swing.JButton();
        btkali = new javax.swing.JButton();
        tujuh = new javax.swing.JButton();
        jtxttampilan = new javax.swing.JTextField();
        sin = new javax.swing.JButton();
        btclear1 = new javax.swing.JButton();
        btpersen1 = new javax.swing.JButton();
        btmodulus = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        log = new javax.swing.JButton();
        btpangkat4 = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator Sederhana");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        lima.setText("5");
        lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limaActionPerformed(evt);
            }
        });
        jPanel1.add(lima);
        lima.setBounds(140, 240, 60, 40);

        sembilan.setText("9");
        sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanActionPerformed(evt);
            }
        });
        jPanel1.add(sembilan);
        sembilan.setBounds(240, 190, 60, 40);

        bthapus.setBackground(new java.awt.Color(102, 255, 255));
        bthapus.setText("akar");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });
        jPanel1.add(bthapus);
        bthapus.setBounds(240, 140, 60, 40);

        bttambah.setBackground(new java.awt.Color(102, 255, 255));
        bttambah.setText("+");
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });
        jPanel1.add(bttambah);
        bttambah.setBounds(330, 290, 60, 40);

        enam.setText("6");
        enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamActionPerformed(evt);
            }
        });
        jPanel1.add(enam);
        enam.setBounds(240, 240, 60, 40);

        btkurang.setBackground(new java.awt.Color(102, 255, 255));
        btkurang.setText("-");
        btkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkurangActionPerformed(evt);
            }
        });
        jPanel1.add(btkurang);
        btkurang.setBounds(330, 340, 60, 40);

        delapan.setText("8");
        delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanActionPerformed(evt);
            }
        });
        jPanel1.add(delapan);
        delapan.setBounds(140, 190, 60, 40);

        dua.setText("2");
        dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaActionPerformed(evt);
            }
        });
        jPanel1.add(dua);
        dua.setBounds(140, 290, 60, 40);

        tiga.setText("3");
        tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaActionPerformed(evt);
            }
        });
        jPanel1.add(tiga);
        tiga.setBounds(240, 290, 60, 40);

        btbagi.setBackground(new java.awt.Color(102, 255, 255));
        btbagi.setText("/");
        btbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbagiActionPerformed(evt);
            }
        });
        jPanel1.add(btbagi);
        btbagi.setBounds(330, 240, 60, 40);

        empat.setText("4");
        empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatActionPerformed(evt);
            }
        });
        jPanel1.add(empat);
        empat.setBounds(40, 240, 60, 40);

        nol.setText("0");
        nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolActionPerformed(evt);
            }
        });
        jPanel1.add(nol);
        nol.setBounds(140, 340, 60, 40);

        btkoma.setText(",");
        btkoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkomaActionPerformed(evt);
            }
        });
        jPanel1.add(btkoma);
        btkoma.setBounds(240, 340, 60, 40);

        btsamadengan.setBackground(new java.awt.Color(102, 255, 255));
        btsamadengan.setText("=");
        btsamadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsamadenganActionPerformed(evt);
            }
        });
        jPanel1.add(btsamadengan);
        btsamadengan.setBounds(40, 450, 260, 40);

        satu.setText("1");
        satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuActionPerformed(evt);
            }
        });
        jPanel1.add(satu);
        satu.setBounds(40, 290, 60, 40);

        btkali.setBackground(new java.awt.Color(102, 255, 255));
        btkali.setText("X");
        btkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkaliActionPerformed(evt);
            }
        });
        jPanel1.add(btkali);
        btkali.setBounds(330, 190, 60, 40);

        tujuh.setText("7");
        tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhActionPerformed(evt);
            }
        });
        jPanel1.add(tujuh);
        tujuh.setBounds(40, 190, 60, 40);
        jPanel1.add(jtxttampilan);
        jtxttampilan.setBounds(40, 30, 350, 100);

        sin.setBackground(new java.awt.Color(102, 255, 255));
        sin.setText("sin");
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });
        jPanel1.add(sin);
        sin.setBounds(40, 390, 60, 40);

        btclear1.setBackground(new java.awt.Color(102, 255, 255));
        btclear1.setText("C");
        btclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclear1ActionPerformed(evt);
            }
        });
        jPanel1.add(btclear1);
        btclear1.setBounds(330, 140, 60, 40);

        btpersen1.setBackground(new java.awt.Color(102, 255, 255));
        btpersen1.setForeground(new java.awt.Color(51, 51, 51));
        btpersen1.setText("%");
        btpersen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpersen1ActionPerformed(evt);
            }
        });
        jPanel1.add(btpersen1);
        btpersen1.setBounds(140, 140, 60, 40);

        btmodulus.setBackground(new java.awt.Color(102, 255, 255));
        btmodulus.setText("Mod");
        btmodulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodulusActionPerformed(evt);
            }
        });
        jPanel1.add(btmodulus);
        btmodulus.setBounds(40, 140, 60, 40);

        cos.setBackground(new java.awt.Color(102, 255, 255));
        cos.setText("cos");
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });
        jPanel1.add(cos);
        cos.setBounds(140, 390, 60, 40);

        tan.setBackground(new java.awt.Color(102, 255, 255));
        tan.setText("tan");
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });
        jPanel1.add(tan);
        tan.setBounds(240, 390, 60, 40);

        log.setBackground(new java.awt.Color(102, 255, 255));
        log.setText("log");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        jPanel1.add(log);
        log.setBounds(330, 390, 60, 40);

        btpangkat4.setBackground(new java.awt.Color(102, 255, 255));
        btpangkat4.setText("X2");
        btpangkat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpangkat4ActionPerformed(evt);
            }
        });
        jPanel1.add(btpangkat4);
        btpangkat4.setBounds(40, 340, 60, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 550, 500);

        setSize(new java.awt.Dimension(437, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
        // TODO add your handling code here:
        bil1 = Double.parseDouble(Bilangan);
        jtxttampilan.setText("+");
        Bilangan = "";
        pilih=1;

        
    }//GEN-LAST:event_bttambahActionPerformed

    private void duaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaActionPerformed
        // TODO add your handling code here:
         Bilangan +="2";
        jtxttampilan.setText(Bilangan);
    }//GEN-LAST:event_duaActionPerformed

    private void satuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuActionPerformed
        // TODO add your handling code here:
        Bilangan +="1";
        jtxttampilan.setText(Bilangan);
    }//GEN-LAST:event_satuActionPerformed

    private void tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaActionPerformed
        // TODO add your handling code here:
        Bilangan +="3";
        jtxttampilan.setText(Bilangan);
    }//GEN-LAST:event_tigaActionPerformed

    private void empatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatActionPerformed
        // TODO add your handling code here:
       Bilangan +="4";
        jtxttampilan.setText(Bilangan);
    }//GEN-LAST:event_empatActionPerformed

    private void limaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaActionPerformed
        // TODO add your handling code here:
        Bilangan +="5";
        jtxttampilan.setText(Bilangan);
    }//GEN-LAST:event_limaActionPerformed

    private void enamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamActionPerformed
        // TODO add your handling code here:
        Bilangan +="6";
        jtxttampilan.setText(Bilangan);
    }//GEN-LAST:event_enamActionPerformed

    private void sembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanActionPerformed
        // TODO add your handling code here:
        Bilangan +="9";
        jtxttampilan.setText(Bilangan);
    }//GEN-LAST:event_sembilanActionPerformed

    private void delapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanActionPerformed
        // TODO add your handling code here:
        Bilangan +="8";
        jtxttampilan.setText(Bilangan);
    }//GEN-LAST:event_delapanActionPerformed

    private void tujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhActionPerformed
        // TODO add your handling code here:
       Bilangan +="7";
        jtxttampilan.setText(Bilangan);
    }//GEN-LAST:event_tujuhActionPerformed

    private void btsamadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsamadenganActionPerformed
        // TODO add your handling code here:
        switch(pilih){
            case 1:
                bil2 = Double.parseDouble(String.valueOf(jtxttampilan.getText()));
                jumlah = bil1+bil2;
                Bilangan = Double.toString(jumlah);
                break;
            case 2:
                bil2 = Double.parseDouble(String.valueOf(jtxttampilan.getText()));
                jumlah = bil1-bil2;
                Bilangan = Double.toString(jumlah);
                break;
             case 3:
                bil2 = Double.parseDouble(String.valueOf(jtxttampilan.getText()));
                jumlah = bil1*bil2;
                Bilangan = Double.toString(jumlah);
                break;
             case 4:
                bil2 = Double.parseDouble(String.valueOf(jtxttampilan.getText()));
                jumlah = bil1/bil2;
                Bilangan = Double.toString(jumlah);
                break;
            case 5:
                bil2 = Double.parseDouble(String.valueOf(jtxttampilan.getText()));
                jumlah = bil1%bil2;
                Bilangan = Double.toString(jumlah);
                break;
             case 6:
                bil2 = Double.parseDouble(String.valueOf(jtxttampilan.getText()));
                jumlah = bil1 / 100; 
                Bilangan = Double.toString(jumlah);
                break;   
            case 7:
                bil2 = Double.parseDouble(String.valueOf(jtxttampilan.getText()));
                jumlah = Math.pow(bil1, bil2);
                Bilangan = Double.toString(jumlah);
                break;
            case 8:
                bil2 = Double.parseDouble(String.valueOf(jtxttampilan.getText()));
                jumlah = Math.sqrt(bil1);
                Bilangan = Double.toString(jumlah);
                break;
            case 9:
                bil2 = Double.parseDouble(String.valueOf(jtxttampilan.getText()));
                jumlah = Math.sin(bil1);
                Bilangan = Double.toString(jumlah);
                break;
            case 10:
                bil2 = Double.parseDouble(String.valueOf(jtxttampilan.getText()));
                jumlah = Math.cos(bil1);
                Bilangan = Double.toString(jumlah);
                break;
            case 11:
                bil2 = Double.parseDouble(String.valueOf(jtxttampilan.getText()));
                jumlah = Math.tan(bil1);
                Bilangan = Double.toString(jumlah);
                break;
            case 12:
                bil2 = Double.parseDouble(String.valueOf(jtxttampilan.getText()));
                jumlah = Math.log(bil1);
                Bilangan = Double.toString(jumlah);
                break;
        }
        jtxttampilan.setText(Bilangan);
    }//GEN-LAST:event_btsamadenganActionPerformed
              
    private void btkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkurangActionPerformed
        // TODO add your handling code here:
         bil1 = Double.parseDouble(Bilangan);
        jtxttampilan.setText("-");
        Bilangan = "";
        pilih=2;
    }//GEN-LAST:event_btkurangActionPerformed

    private void btkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkaliActionPerformed
        // TODO add your handling code here:
          bil1 = Double.parseDouble(Bilangan);
        jtxttampilan.setText("*");
        Bilangan = "";
        pilih=3;
    }//GEN-LAST:event_btkaliActionPerformed

    private void btbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbagiActionPerformed
        // TODO add your handling code here:
          bil1 = Double.parseDouble(Bilangan);
        jtxttampilan.setText("/");
        Bilangan = "";
        pilih=4;
    }//GEN-LAST:event_btbagiActionPerformed

    private void btclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclear1ActionPerformed
        // TODO add your handling code here:
          jtxttampilan.setText(null);
        bil1=0.0;
        bil2=0.0;
        jumlah=0.0;
        Bilangan="";
    }//GEN-LAST:event_btclear1ActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
        // TODO add your handling code here:
         bil1 = Double.parseDouble(Bilangan);
        
        Bilangan = "";
        jumlah = Math.sin(bil1);
                Bilangan = Double.toString(jumlah);
        jtxttampilan.setText(Bilangan);
    }//GEN-LAST:event_sinActionPerformed

    private void nolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolActionPerformed
        // TODO add your handling code here:
         Bilangan +="0";
        jtxttampilan.setText(Bilangan);
    }//GEN-LAST:event_nolActionPerformed

    private void btpersen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpersen1ActionPerformed
        // TODO add your handling code here:
         bil1 = Double.parseDouble(Bilangan);
        Bilangan = "";
                jumlah = bil1 / 100; 
                Bilangan = Double.toString(jumlah);
         jtxttampilan.setText(Bilangan);
        
        
    }//GEN-LAST:event_btpersen1ActionPerformed

    private void btmodulusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodulusActionPerformed
        // TODO add your handling code here:
         bil1 = Double.parseDouble(Bilangan);
        jtxttampilan.setText("mod");
        Bilangan = "";
        pilih=5;
    }//GEN-LAST:event_btmodulusActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
         bil1 = Double.parseDouble(Bilangan);
        jtxttampilan.setText("akar");
        Bilangan = "";
        pilih=8;
    }//GEN-LAST:event_bthapusActionPerformed

    private void btkomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkomaActionPerformed
        // TODO add your handling code here:
          Bilangan +=",";
        jtxttampilan.setText(Bilangan);
    }//GEN-LAST:event_btkomaActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
        // TODO add your handling code here:
          bil1 = Double.parseDouble(Bilangan);
        
        Bilangan = "";
        jumlah = Math.cos(bil1);
                Bilangan = Double.toString(jumlah);
        jtxttampilan.setText(Bilangan);
       
    }//GEN-LAST:event_cosActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
        // TODO add your handling code here:
         bil1 = Double.parseDouble(Bilangan);
        
        Bilangan = "";
        jumlah = Math.tan(bil1);
                Bilangan = Double.toString(jumlah);
        jtxttampilan.setText(Bilangan);
  
    }//GEN-LAST:event_tanActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        // TODO add your handling code here:
          bil1 = Double.parseDouble(Bilangan);
        
        Bilangan = "";
        jumlah = Math.log(bil1);
                Bilangan = Double.toString(jumlah);
        jtxttampilan.setText(Bilangan);
    }//GEN-LAST:event_logActionPerformed

    private void btpangkat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpangkat4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btpangkat4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbagi;
    private javax.swing.JButton btclear1;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btkali;
    private javax.swing.JButton btkoma;
    private javax.swing.JButton btkurang;
    private javax.swing.JButton btmodulus;
    private javax.swing.JButton btpangkat4;
    private javax.swing.JButton btpersen1;
    private javax.swing.JButton btsamadengan;
    private javax.swing.JButton bttambah;
    private javax.swing.JButton cos;
    private javax.swing.JButton delapan;
    private javax.swing.JButton dua;
    private javax.swing.JButton empat;
    private javax.swing.JButton enam;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField jtxttampilan;
    private javax.swing.JButton lima;
    private javax.swing.JButton log;
    private javax.swing.JButton nol;
    private javax.swing.JButton satu;
    private javax.swing.JButton sembilan;
    private javax.swing.JButton sin;
    private javax.swing.JButton tan;
    private javax.swing.JButton tiga;
    private javax.swing.JButton tujuh;
    // End of variables declaration//GEN-END:variables
}
